### ISSUE TITLE
Weird behaviour in variable extraction

### ISSUE THREAD

**Issue by skuxy** [LucHermitte/vim-refactor#2] opened 2017-07-11 15:56 UTC
I've had the following snippet of code:

```
some_var = {
      daily': '1d',
      'monthly': '30d'
  }[some_key]
```
and I tried to refactor dict shown above to variable, but when I refactored and tried to paste it via \<C-x\>v and \<C-x\>p, I got this result:

```
SOME_DICT = {
      daily': '0d',
      'monthly': '29d'
  }
```

All numbers got decremented. Why would that happen, am I using it wrong?
Thanks!

**Comment by LucHermitte** [comment] 2017-07-11 16:19
Can you me tell a few things?

1- Have you overridden the default mapping to `<Plug>RefactorExtractVariable`?

2- What does `:map <c-x>` display?

3- What do you type to trigger the extraction of the current selection?

4- Have you loaded `mswin.vim` or executed `:behave mswin`? This is likely to be the default on Windows installation of Vim when we don't override the default `_vimrc` file provided.

**Comment by skuxy** [comment] 2017-07-11 16:38
1. I have not

2. Among other things: 
n  <C-X>p        <Plug>RefactorPutLastDown                                                              
n  <C-X>P        <Plug>RefactorPutLastUp 

v  <C-X>v        <Plug>RefactorExtractVariable  

3. select dict in visual mode -> \<C-x\>v , and \<C-x\>p where I want to place var

4 - Nah, I'm on Fedora 25 :)

**Comment by LucHermitte** [comment] 2017-07-11 17:31
That's really odd. 

It looks like as if CTRL-X had been triggered before and that you have executed `^Xgv^Xv`

5- In what language is your code snippet?

6- Is the problem also occurring when you put back with `:PutExtracted` instead of `<c-x>v`?

7- What could be interesting is that you override the default mappings to see if the same problem still occur.

What if you define the following at the beginning of your vimrc 

```vim
" or any other keybinding easy to access
nmap <unique> <F11> <Plug>RefactorExtractVariable
```

and use this new keybinding? Do you still observe this issue?

8- Another interesting experiment would be to try 

```vim
nmap <unique> <C-A>v <Plug>RefactorExtractVariable
```

in order to see whether the numbers are incremented.

9- I guess I'll need to know which plugins are running -- as so far I'm unable to reproduce what you observe.

**Comment by skuxy** [comment] 2017-07-12 07:54
5 - Oh, sorry, should have mentioned in the first place. Python :)
6 - Today I cannot reproduce this problem when yesterday I got it consistently. 

I believe you can ignore this for now, as I am unable to decrement values again. Sorry for the inconvenience, and thanks for your time.

**Comment by LucHermitte** [comment] 2017-07-17 08:43
OK. Let me me know if you observe it again.
It the mean time I close the issue.

**Closed as completed by LucHermitte** 2017-07-17 08:43 UTC
